dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

env:
  global:
    - COVERALLS_PARALLEL=true

install:
  - pip install -r requirements.txt

script:
  - pylint cons/ tests/
  - if [[ `command -v black` ]]; then
      black --check cons tests;
    fi
  - pytest -v tests/ --cov=cons/

after_success:
  - coveralls

notifications:
  webhooks: https://coveralls.io/webhook
